[template]
src   = "AWS_SECRET_ACCESS_KEY"
dest  = "/etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY"
uid = 0
gid = 106
mode  = "0640"
keys = [
  "/deis/store/gateway",
]
check_cmd = "/app/bin/check {{ .src }}"
